config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'
  resources :posts, except: :destroy do
    resources :comments, only: :create
  end

  resources :categories, except: :destroy

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :post_categories
  has_many :posts, through: :post_categories
  
  validates :name, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  validates :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User' 
  has_many :comments, dependent: :destroy
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, presence: true, length: {minimum: 5}
  validates :url, presence: true, uniqueness: true
  validates :description, presence: true
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :post  
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_catagory, only: [:show, :edit, :update]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Your category has been added."
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    
  end

  def edit; end

  def update

    if @category.update(category_params)
      flash[:notice] = "Your category has been updated"
      redirect_to posts_path
    else
      render :edit
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_catagory
    @category = Category.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(set_comment)
    @comment.creator = User.first # TODO: Change to current user
    @comments = @post.comments.all
    if @comment.save
      flash[:notice] = "Your comment has been posted"
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  private

  def set_comment
    params.require(:comment).permit(:body)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:show, :edit, :update]

  def index
    @posts = Post.all
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.creator = User.first # TODO: This will need to be changed when we add authentication!
    if @post.save
      flash[:notice] = "Your post was created."
      redirect_to posts_path
    else
      render :new  
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      flash[:notice] = "You post has been updated!"
      redirect_to post_path(@post)
    else
        render :edit
    end
  end

private
  def post_params
    params.require(:post).permit(:url, :title, :description, category_ids: [])
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def fix_url(str)
    str.starts_with?('http://') ? str : "http://#{str}"
  end

  def fix_date(dt)
    dt.strftime("%m/%d/%Y %l:%M%P %Z")
  end
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %></span>

app/views/categories/_form.html.erb
<%= render 'shared/alert', alert: @category.errors %>

<%= form_for @category do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br/>
  <%= f.submit(@category.new_record? ? "Create Category" : "Edit Category", class: 'btn btn-primary') %>
<% end %>

app/views/categories/edit.html.erb
<%= render 'form' %>

app/views/categories/index.html.erb
<h1>Select Category to Edit</h1>

<% @categories.each do |cat| %>
  <%= cat.name %>
  <%= link_to "Edit", edit_category_path(cat) %>
  <br/>
<% end %>

app/views/categories/new.html.erb
<%= render 'form' %>

app/views/categories/show.html.erb
<% header = link_to("All Posts", posts_path) + " &raquo; #{@category.name}".html_safe%>
<%= render 'shared/content_title', title: header %>

<%= render 'shared/posts', posts: @category.posts %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
</ul>

<div class='btn-group nav_item'>
    <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
      Categories <span class='caret'></span>
    <% end %>
    <ul class='dropdown-menu'>
      <% Category.all.each do |category| %>
        <li>
          <%= link_to category.name, category_path(category) %>
        </li>
      <% end %>
      <li class='divider'></li>
      <li>
        <%= link_to(categories_path) do %>
          Edit Category
        <% end %>
      </li>
      <li class='divider'></li>
      <li>
        <%= link_to(new_category_path) do %>
          <i class='icon-plus'></i>
          New Category
        <% end %>
      </li>
    </ul>
</div>
<div class='nav-item'>
  <%= link_to 'New Post', new_post_path, class: 'btn btn-success btn-small' %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_form.html.erb
<%= render 'shared/alert', alert: @post.errors %>

<div class= 'well span8'>

<%= form_for @post do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>
  <br/>
  <%= f.label :url %>
  <%= f.text_field :url %>
  <br/>
  <%= f.label :description %>
  <%= f.text_area :description, rows: 5 %>
  <br/>

  <% Category.all.each do |category| %>
    <%= check_box_tag("post[category_ids][]", category.id, @post.categories.include?(category)) %>
    <%= category.name %>
  <% end %>

  <br/>
  <%= f.submit(@post.new_record? ? 'Create Post' : 'Update Post', class: 'btn btn-primary') %>
<% end %>
</div>

app/views/posts/edit.html.erb
<h4>Edit Posts</h4>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: 'All Posts' %>

<%= render 'shared/posts', posts: @posts %>

app/views/posts/new.html.erb
<h4>Add New Posts</h4>

<%= render 'form' %>

app/views/posts/show.html.erb
<p class='pull-right'>
  [<%= link_to "Edit this post", edit_post_path(@post) %>]
</p>
<p>
  <%= render @post.categories %>
</p>

<% title_link = link_to(@post.title, fix_url(@post.url)) %>

<%= render 'shared/content_title', title: title_link %>

  <p><%= @post.description %></p>
  <br/>
  <hr/>

<%= render 'shared/alert', alert: @comment.errors %>

<%= form_for [@post, @comment] do |f| %>
  <div class='control-group'>
    <%= f.label :body, "Leave a comment" %>
    <%= f.text_area :body, rows: 5, class: 'span4'%>
    <br/>
    <%= f.submit "Create Comments", class: 'btn btn-primary'%>
  </div
<% end %>

<!--Iterate through all comments-->
<h5>Comments:</h5>

  <% @post.comments.each do |comment| %>
    <div class = "row">
      <div class='well span8'>
        <em>"<%= comment.body %>"</em>
        <br/>
          <span class='quiet'>commented </span>
            <% if comment.creator == nil %>

            <% else %>
              by <%= comment.creator.username %>
            <% end %>
          at <%= fix_date(comment.created_at) %>
      </div>
    </div>
  <% end %>

app/views/shared/_alert.html.erb
<% if alert.any? %>
  <div class = "alert alert-error">
    <% alert.full_messages.each do |error|%>
      <%= error %>
    <br/>
    <% end %>
  </div>
<% end %>

app/views/shared/_content_title.html.erb
<p class='lead'>
  <%= title %>
  <hr/>
</p>

app/views/shared/_posts.html.erb
<% posts.each do |post| %>
  <div class="row">
    <div class='span8 well'>
      
      <%= render post.categories %> <!--This passes in each category obj and looks for the category partial in the categories folder -->
      
      <h4><%= link_to post.title, "http://#{post.url}" %></li></h4>
      <p><%= post.description %></p>
      <p>
        <span class='quiet'>posted </span>
          <% if post.creator == nil %>

          <% else %>
            by <%= post.creator.username %>
          <% end %>
        at <%= fix_date(post.created_at) %>
      </p>
      <span>
        <%= link_to "#{post.comments.size} comments", post_path(post) %>
      </span>
    </div>
  </div>
<% end %>